### ISSUE TITLE
No v1.2 in the central repo of maven 

### ISSUE THREAD

**Issue by fjjiaboming** [AdoHe/etcd4j#7]
Why?

**Comment by AdoHe** [comment]
@fjjiaboming I just forget about this. Can you help to upload v1.2 to the central repo of maven. :+1:

**Comment by fjjiaboming** [comment]
@AdoHe  I have no account of the central repo...

**Comment by AdoHe** [comment]
@fjjiaboming ok, later I will upload this to central maven. Sorry about that.

**Comment by fjjiaboming** [comment]
When ?

**Comment by AdoHe** [comment]
@fjjiaboming I think tomorrow I will push this to central maven.

**Comment by AdoHe** [comment]
@fjjiaboming I just upload 1.2 to central maven. You may have a try.
