### ISSUE TITLE
Is there returnValue underlying one atomic operation?

### ISSUE THREAD

**Issue by fjjiaboming** [AdoHe/etcd4j#8]
I see one API in 1.2

```
public void set(String key, String value, Integer ttl, Boolean prevExist) throws EtcdClientException
```
But it is not with returnValue. 
I except that some clients concurrently access the proxy under that only one can get the lock ( set key-value is OK).

**Comment by AdoHe** [comment]
@fjjiaboming Ok, I will look into.

**Comment by fjjiaboming** [comment]
So now I get key and judge the value after having setted key  ,   that I can regard as one atomic operation judge.

**Comment by AdoHe** [comment]
@fjjiaboming So if you have better solution you may open a PR.

**Comment by fjjiaboming** [comment]
OK. 
I need some time to know the ETCD.

**Comment by AdoHe** [comment]
@fjjiaboming Ok, you can visit this link: `https://github.com/coreos/etcd/blob/master/Documentation/api.md` for more references.

**Comment by fjjiaboming** [comment]
@AdoHe   ok
