### ISSUE TITLE
Many method returnValue is void.

### ISSUE THREAD

**Issue by fjjiaboming** [AdoHe/etcd4j#9]
How can I judge the result whether is successful ?

**Comment by AdoHe** [comment]
@fjjiaboming You have no need to do any more judgement, I have did that for you. For example if you are calling `set` operation, if there is no any exceptions thrown, the result is successful, and if exceptions thrown the operation is something wrong.

**Comment by AdoHe** [comment]
@fjjiaboming For the method return value is void, since actually we don't need this result value, so I did't give any return value.

**Comment by fjjiaboming** [comment]
So you mean that you use exceptions as the meaning.

**Comment by AdoHe** [comment]
@fjjiaboming if there is any error, no matter network error or etcd related error, it will throw exceptions. I am considering adding return value since it maybe useful in some use cases.

**Comment by fjjiaboming** [comment]
@AdoHe  Yes. 
And  "void" keyword has no meaningful anything.

**Comment by AdoHe** [comment]
@fjjiaboming Maybe when etcd v3 api is stable, wen can update this.

**Comment by AdoHe** [comment]
close this as we are implementing a new v3 client.
